### ISSUE TITLE
Cannot use CentOS6 image for ansible role tests.

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/docker-centos6-ansible#1]
I'm unsure if you're aware of this, but I've been trying to use the CentOS6 image as recommended by you, in the same standard format a lot of your other roles use, and I simply... can't - anymore.

Here's the error message provided by Travis.

````
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/lib/systemd/systemd\\\": stat /usr/lib/systemd/systemd: no such file or directory\"\n".
````

**Comment by fubarhouse** [comment]
I've managed to get around this completely by using /sbin/init instead, so maybe the documentation simply needs changing? I'll leave it in your court, but I'm now building successfully again.

**Comment by geerlingguy** [comment]
Oops! Sorry about that; fixed with the above commit. You're correct that it should be `/sbin/init`.

**Comment by fubarhouse** [comment]
My apologies for drawing your attention here again...

This was working until recently, and now I'm having the same problem with /sbin/init

````
docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/sbin/init\\\": stat /sbin/init: no such file or directory\"\n".
````

Other than dropping my support for this platform - would you have anything to suggest?

**Comment by fubarhouse** [comment]
Never mind, this seems like an issue with travis...

**Comment by geerlingguy** [comment]
Ha, no worries... it wasn't just you! https://github.com/geerlingguy/docker-centos6-ansible/issues/2

I had to fix that yesterday to get CentOS 6 tests happy again :)
